// Allocation Scope
pub const VK_SYSTEM_ALLOCATION_SCOPE_COMMAND: u32 = 0;
pub const VK_SYSTEM_ALLOCATION_SCOPE_OBJECT: u32 = 1;
pub const VK_SYSTEM_ALLOCATION_SCOPE_CACHE: u32 = 2;
pub const VK_SYSTEM_ALLOCATION_SCOPE_DEVICE: u32 = 3;
pub const VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE: u32 = 4;